<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    
    <xacro:property name="footprint_radius" value="0.001" />
    <!-- 1.添加base_footprint -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}"/>
            </geometry>
        </visual>
    </link>

    
    <xacro:property name="base_radius" value="0.1" />
    <xacro:property name="base_length" value="0.08" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:property name="base_joint_z" value="${base_length/2 + lidi}" />
    <!-- 2. 底盘  -->
    <!-- 2.1. link -->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.08" />
            </geometry>
            
            <origin xyz="0 0 0" rpy="0 0 0" />

            <material name="baselink_color">
                <color rgba="1 0.5 0.2 0.7" />
            </material>
        </visual>
    </link>
    <!-- 2.2. joint -->
    <joint name="link2footprint" type="fixed"> 
        <parent link="base_footprint" />
        <child link="base_link" />
        <!-- 关节z上的设置 = 车体高度/2 + 离地间距 -->
        <origin xyz="0 0 0.055" rpy="0 0 0" />
    </joint>


    <xacro:property name="wheel_radius" value="0.0325" /><!-- 半径 -->
    <xacro:property name="wheel_length" value="0.015" /><!-- 宽度 -->
    <xacro:property name="PI" value="3.1415926" /><!-- 宽度 -->
    <xacro:property name="wheel_joint_z" value="${-(base_length/2 + lidi - wheel_radius)}" /><!-- 宽度 -->
    
    <!-- 
        wheel_name: left or right
        flag: 1 or -1
     -->
    <xacro:macro name="wheel_func" params="wheel_name flag">
    <!-- 3.驱动轮  -->
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />

                <material name="wheel_color">
                    <color rgba="0 0 0 0.9" />
                </material>
            </visual>
        </link>

        <joint name="${wheel_name}2link" type="continuous"> 
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <!-- z=0.055-0.0325 -->
            <origin xyz="0 ${0.1 * flag} ${wheel_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint> 
    </xacro:macro>   

    <xacro:property name="small_wheel_radius" value="0.0075" /><!-- 半径 -->
    <!-- z的偏移量=车体高度/2 + 离地间距 - 万向轮半价 -->
    <xacro:property name="small_joint_z" value="${-(base_length/2 + lidi - small_wheel_radius)}" />

    <xacro:macro name="small_wheel_func" params="small_wheel_name flag">
        <!-- 4.万向轮  -->
        <!-- 4.1 link -->
        <link name="${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${small_wheel_radius}" />
                </geometry>
                
                <origin xyz="0 0 0" rpy="0 0 0" />

                <material name="wheel_color">
                    <color rgba="0 0 0 0.9" />
                </material>
            </visual>
        </link>
        <!-- 4.2 joint -->
        <joint name="${small_wheel_name}2link" type="continuous"> 
            <parent link="base_link" />
            <child link="${small_wheel_name}_wheel" />
            <!-- z=0.055-0.0325 -->
            <origin xyz="${0.08 * flag} 0 ${small_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>   
    </xacro:macro>  

    <!-- 调用宏 -->
    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />
    <xacro:small_wheel_func small_wheel_name="front" flag="1" />
    <xacro:small_wheel_func small_wheel_name="back" flag="-1" />
    

</robot>